apiVersion: v1
kind: Namespace
metadata:
  name: ronalt
  labels:
    name: ronalt
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ronalt-deployment
  namespace: ronalt
  labels:
    app: app1-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ronalt
  template:
    metadata:
      labels:
        app: ronalt
    spec:
      containers:
        - name: ronalt
          image: ronaldschouw/hello-openshift
          ports:
            - containerPort: 8080  

---
apiVersion: v1
kind: Service
metadata:
  name: ronalt-service
  namespace: ronalt
  labels:
    app: ronalt
spec:
  type: ClusterIP
  selector:
    app: ronalt
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ronalt
  namespace: ronalt
  annotations:
    kubernetes.io/ingress.class: nginx  
spec:  
  rules:
  - http:
      paths:
      - path: /ronalt
        backend:
          serviceName: ronalt
          servicePort: 8080
