apiVersion: v1
kind: Namespace
metadata:
  name: default
  labels:
    name: default
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: default-deployment
  namespace: default
  labels:
    app: app1-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: default
  template:
    metadata:
      labels:
        app: default
    spec:
      containers:
        - name: default
          image: ronaldschouw/oliebollen_pod:2022
          ports:
            - containerPort: 8080  

---
apiVersion: v1
kind: Service
metadata:
  name: default-service
  namespace: default
  labels:
    app: default
spec:
  type: NodePort
  selector:
    app: default
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 32022
